# Generated by Django 4.1.4 on 2022-12-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_ads_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
